#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Requirements:
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

# Install HAproxy
apt-get -y update
apt-get install -y haproxy

# Load balancing configuration
printf %s "
frontend http
    bind *:80
    mode http    
    default_backend web-backend

backend web-backend
    balance roundrobin
    option forwardfor
    server 32459-web-01 100.25.169.98 check
    server 32459-web-02 34.239.248.5 check
" >> /etc/haproxy/haproxy.cfg

printf %s "
ENABLED=1
" >> /etc/default/haproxy

service haproxy restart
