#!/usr/bin/env bash
# configure SSH client to connect to server without typing a password

Host server1
    HostName 54.236.48.101
    User ubuntu
    passwordAuthentification no
    IdentityFile ~/.ssh/school
